### ISSUE TITLE
dropbear_initrd_encrypt on BeagleBone black

### ISSUE THREAD

**Issue by strasharo** [grazzolini/dropbear_initrd_encrypt#2]
Hello,

I'm wondering if anyone has succeeded to have a fully encrypted Arch installation on a BeagleBone Black using dropbear_initrd_encrypt ?
I have currently a working Raspberry PI B with FDE + remote unlock via ssh, which I set up using the instructions from https://gist.github.com/pezz/5310082 and http://blog.epijunkie.com/2014/01/raspberry-pi-arch-linux-fde-freeradius3-a-low-power-radius-server-for-wpa2-enterprise/, however since the boot configuration of the BBB is a bit different, I'm a little bit puzzled what has to be added (to uEnv.txt?) in order to get it working. :?
Any tips and tricks are welcome. :)

Thank you.

**Comment by grazzolini** [comment]
I'm not familiar with the differences between the boot of the Raspberry PI and the BeagleBone Black. Also, both the instructions are a bit outdated, from what I saw. But, since this hook doesn't care for the boot process, if you can manage to get both your kernel and initramfs loaded, and at least have parameters passed to the kernel, it will work.

**Comment by strasharo** [comment]
Is there a place with up to date instructions for dropbear_initrd_encrypt?

**Comment by grazzolini** [comment]
I took a quick look yesterday at Uboot documentation. I don't know if it can load both a kernel and a initrd as other boot loaders can. But, you could probably load GRUB or other boot loader and have it load your kernel and initramfs. Without an actual hardware for testing, I can't really help you. The only thing this hook need is a network interface. As I mentioned, if you can make your initramfs load, it will run.

**Comment by strasharo** [comment]
Thanks a lot for the tips Giancarlo, really appreciated. :)
