### ISSUE TITLE
Integration with mkinitcpio-chkcryptoboot

### ISSUE THREAD

**Issue by ser** [grazzolini/dropbear_initrd_encrypt#8]
Because dropbear_initrd_encrypt operates on an unencrypted boot partition, it should provide a method to verify consistency of the content. It can be provided by mkinitcpio-chkcryptoboot package, but this hook should report the potential break-in through sshd, for example using its "Banner" option.

I am open to discuss the topic and work on it after we reach a consensus.

**Comment by grazzolini** [comment]
@ser 
I'm afraid the chkcryptoboot hook can't help in this case. That hook is meant as an additional layer of security, when you have a separate boot partition, which is also encrypted and, of course, with a different password than your root partition. It can be used on an unencrypted boot partition, of course, but it won't be as effective as in it's intended original use. I have plans for merging the mkinitcpio-chkcryptoboot, and the chkboot packages.

In this situation of remote unlocking, there isn't much that can be done. Perhaps antievilmaid with a TPM chip, and other forms of securing the pre-boot. But anything that requires manual intervention before the initramfs, will make this hook loose it's purpose.

Cheers,
Giancarlo Razzolini

**Comment by ser** [comment]
Chkcryptoboot operates on unencrypted partition and it's effectiveness is much better than no check at all. Merging is OK for me :) I am mostly interested in security of remote KVM instances, so TPM is not useful at all.

**Comment by grazzolini** [comment]
@ser 

When chkcryptoboot gets merged with chkboot, you'll have both a premount check (chkcryptoboot) and a postmount check (chkboot). Right now, dropbear_initrd_encrypt won't show any of the chkcryptoboot messages, not even if your boot loader was, indeed, modified. As I mentioned, I'm splitting this hook, so it'll be easier to change things, specially the shell used to unlock the root partition. It will make it easier to customize the process, perhaps by adding a shell that calls the same code as chkcryptoboot does, but when logging in remotely, and displaying the messages, also to the remote shell.
